title: Hypertext
author: Guy Russell
email: squifeatures@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Linking things to other things

# social links
twitter_username: squidfeatures # DO NOT include the @ character, or else the build will fail!
github_username:  squidfeatures # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
